[en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-GB'
    languageDirection = 'ltr'
    languageName = 'English'
    [en.pagination]
        disableAliases = false
        pagerSize = 12
        path = 'page'

[zh-CN]
    contentDir = 'content/zh-CN'
    disabled = false
    languageCode = 'zh-CN'
    languageDirection = 'ltr'
    languageName = '中文'
    [zh-CN.pagination]
        disableAliases = false
        pagerSize = 4
        path = 'page'
